# Site Info
title: Lectio Humana
tagline: 'A homo erectus fossil was stolen from a museum. Homo ereptus.'
description: 'An exploration of the Christian classical humanist tradition.'
# baseurl: "/lanyon"
url: http://lectiohumana.com
blogurl: /blog
logo: '/public/logo.png'
ogimage: '/public/img/humanists.png'
bookurl: 'https://drive.google.com/file/d/1sIq_inG0vEUh27IGXB-P7Ysu4o630V9p/view?usp=sharing'
permalink: /blog/:title

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 3
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Felipe Vogel
  contact:
    email:     http://scr.im/felipevogel
#    goodreads: https://www.goodreads.com/user/show/51351645-felipe-vogel
    linkedin:  https://www.linkedin.com/in/vogelfelipe
#    github:    https://github.com/codinfox
    # facebook:  <hide>
#    twitter:   https://twitter.com/Li_Zhihao
#    weibo:     http://weibo.com/41173780
#    http://tny.im/f7z

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Tags: '/blog/tags/' }
  Psalmi:
    - '/psalmi/'
  Ephemeris:
    - '/ephemeris/1/'
  About:          
    - '/about/'
#  Github Project: 
#    - 'http://codinfox.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
#category_page: '/categories/'

# Puglins
plugins:
  - jekyll-seo-tag
mathjax: true # whether support mathjax
google_analytics_token: 
disqus_short_name: 