# Site Info
title: Lectio Humana
tagline: 'Listening to the humanists.'
description: 'Daily readings of humanists. Latin, things classical and Christian, and Jordan Peterson included.'
# baseurl: "/lanyon"
url: http://lectiohumana.com
logo: '/public/logo.png'
ogimage: '/public/img/humanists.png'
# permalink: /:title

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Felipe Vogel
  contact:
    email:     http://scr.im/felipevogel
    youtube: https://www.youtube.com/channel/UCn5bvbdSxoChcEmU28opUTg
    goodreads: https://www.goodreads.com/user/show/51351645-felipe-vogel
    linkedin:  https://www.linkedin.com/in/vogelfelipe
#    github:    https://github.com/codinfox
    # facebook:  <hide>
#    twitter:   https://twitter.com/Li_Zhihao
#    weibo:     http://weibo.com/41173780
#    http://tny.im/f7z

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Index:           
    - '/categories/'
  Tags:
    - '/tags/'
  Ephemeris:
    - '/ephemeris/'
  About:          
    - '/about/'
#  Github Project: 
#    - 'http://codinfox.github.io/'

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'

# Puglins
plugins:
  - jekyll-seo-tag
mathjax: true # whether support mathjax
google_analytics_token: 
disqus_short_name: 

